server:
  port: 8082
  servlet:
    context-path: /api/v1/restaurants

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants_db
    username: restaurant_db
    password: restaurant_db
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: restaurant_management

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: restaurant_management
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    schemas: restaurant_management
    placeholders:
      schema_name: restaurant_management

logging:
  level:
    com.pragma.restaurants: DEBUG
    org.springframework.security: INFO
    org.flywaydb: INFO

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  server-url: http://localhost:8080

users:
  service:
    url: http://localhost:8080